### ISSUE TITLE
RoadMap 2023

### ISSUE THREAD

**Issue by tisonkun** [korandoru/hawkeye#16]
## Features

* [x] #19
* [x] #44
* [x] #20
* [x] #21
* [x] #64
* [x] #69

## Documents

* [ ] https://github.com/korandoru/hawkeye/issues/87

## Refactor

* [x] #22
* [x] #32
* [x] #76
* [ ] https://github.com/korandoru/hawkeye/issues/86

## Miscellaneous

* [ ] Fine-grained usability configs, like `failIfMissing`, `skipExistingHeaders`, `dryRun`, etc. from [license-maven-plugin](https://github.com/mathieucarbou/license-maven-plugin) codebase.
  * `dryRun` is supported at #40.
* [x] Logging properly in hawkeye-core and others.
* [x] #24
* [x] #18
* [x] #73
* [x] #82
* [x] https://github.com/korandoru/hawkeye/issues/85
* [x] https://github.com/korandoru/hawkeye/issues/92

## Research

* [x] #17

**Comment by tisonkun** [comment]
#86 moved to the next year.

#87 I may find time to finish it or just delay :D
